#!/bin/bash

echo "🚀 Setup Cloud SQL - Paso 2: Crear Base de Datos y Ejecutar Schema"
echo "================================================================"
echo ""

# Variables
PROJECT_ID="kashio-squad-nova"
INSTANCE_NAME="aria-db"
DB_NAME="aria"
DB_USER="aria-user"
DB_PASSWORD="AriaKashio2026!"

echo "📊 Cloud SQL Instance Info:"
gcloud sql instances describe $INSTANCE_NAME --project=$PROJECT_ID --format="table(name,state,databaseVersion,settings.tier,ipAddresses[0].ipAddress)"
echo ""

echo "✅ Database '$DB_NAME' ya creada"
echo "✅ Usuario '$DB_USER' ya creado"
echo ""

echo "📝 Paso 3: Ejecutar Schema SQL"
echo "-------------------------------"
echo ""
echo "⚠️  IMPORTANTE: Necesitas tener psql instalado."
echo ""
echo "Opciones para ejecutar el schema:"
echo ""
echo "🔹 Opción 1: Cloud Shell (Recomendado)"
echo "  1. Ve a: https://console.cloud.google.com/sql/instances/aria-db?project=kashio-squad-nova"
echo "  2. Haz clic en 'Open Cloud Shell' (botón superior derecho)"
echo "  3. Ejecuta:"
echo ""
echo "     gcloud sql connect aria-db --user=aria-user --database=aria"
echo "     # Password: AriaKashio2026!"
echo ""
echo "  4. Copia y pega el contenido de: migrations/001_initial_schema.sql"
echo ""
echo "🔹 Opción 2: SQL Editor en Consola"
echo "  1. Ve a: https://console.cloud.google.com/sql/instances/aria-db/databases/aria?project=kashio-squad-nova"
echo "  2. Haz clic en 'SQL Editor'"
echo "  3. Copia y pega el contenido de: migrations/001_initial_schema.sql"
echo "  4. Haz clic en 'Run'"
echo ""
echo "🔹 Opción 3: Instalar psql localmente"
echo "  En macOS: brew install postgresql"
echo "  Luego:"
echo ""
echo "     gcloud sql connect aria-db --user=aria-user --database=aria < migrations/001_initial_schema.sql"
echo ""
echo "================================================================"
echo ""
echo "📍 Connection String (para Cloud Run):"
echo "postgresql://aria-user:AriaKashio2026!@/aria?host=/cloudsql/kashio-squad-nova:us-central1:aria-db"
echo ""
echo "📍 Connection Name:"
echo "kashio-squad-nova:us-central1:aria-db"
echo ""

