/**
 * PDF Generation Service for ARIA
 * 
 * Converts generated artifact content (markdown/text) to professional PDF documents
 * and integrates with Cloud Storage for persistence.
 */

import jsPDF from 'jspdf';
import { marked } from 'marked';

interface ArtifactMetadata {
  title: string;
  initiativeId: string;
  artifactId: string;
  gate: string;
  version: string;
  generatedBy: 'ARIA' | 'Manual';
  author?: string;
  date?: Date;
}

/**
 * Generate PDF from markdown content
 * 
 * @param content - Markdown content from Gemini
 * @param metadata - Artifact metadata
 * @returns PDF as Blob
 */
export async function generatePDF(
  content: string,
  metadata: ArtifactMetadata
): Promise<Blob> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  // Page config
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  // Helper: Add new page if needed
  const checkPageBreak = (requiredSpace: number = 10) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // ==========================================
  // HEADER / COVER PAGE
  // ==========================================
  
  // Logo / Branding
  doc.setFontSize(24);
  doc.setTextColor(79, 70, 229); // Indigo-600
  doc.setFont('helvetica', 'bold');
  doc.text('KASHIO', margin, yPosition);
  
  yPosition += 8;
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // Slate-500
  doc.setFont('helvetica', 'normal');
  doc.text('Fintech Platform', margin, yPosition);
  
  yPosition += 15;
  
  // Document Title
  doc.setFontSize(20);
  doc.setTextColor(15, 23, 42); // Slate-900
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(metadata.title, contentWidth);
  titleLines.forEach((line: string) => {
    doc.text(line, margin, yPosition);
    yPosition += 8;
  });
  
  yPosition += 5;
  
  // Metadata Box
  doc.setFillColor(241, 245, 249); // Slate-100
  doc.rect(margin, yPosition, contentWidth, 35, 'F');
  
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105); // Slate-600
  doc.setFont('helvetica', 'normal');
  
  yPosition += 7;
  doc.text(`Gate: ${metadata.gate}`, margin + 5, yPosition);
  doc.text(`Initiative ID: ${metadata.initiativeId}`, margin + 70, yPosition);
  
  yPosition += 6;
  doc.text(`Artifact ID: ${metadata.artifactId}`, margin + 5, yPosition);
  doc.text(`Version: ${metadata.version}`, margin + 70, yPosition);
  
  yPosition += 6;
  doc.text(`Generated by: ${metadata.generatedBy} AI`, margin + 5, yPosition);
  doc.text(`Date: ${(metadata.date || new Date()).toLocaleDateString('es-ES')}`, margin + 70, yPosition);
  
  yPosition += 6;
  doc.text(`Author: ${metadata.author || 'ARIA System'}`, margin + 5, yPosition);
  
  yPosition += 15;
  
  // Separator line
  doc.setDrawColor(203, 213, 225); // Slate-300
  doc.setLineWidth(0.5);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  
  yPosition += 10;
  
  // ==========================================
  // CONTENT RENDERING
  // ==========================================
  
  // Parse markdown to extract structure
  const sections = parseMarkdownSections(content);
  
  doc.setTextColor(15, 23, 42); // Slate-900
  
  for (const section of sections) {
    checkPageBreak(20);
    
    if (section.type === 'heading1') {
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text(section.content, margin, yPosition);
      yPosition += 8;
      
    } else if (section.type === 'heading2') {
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text(section.content, margin, yPosition);
      yPosition += 7;
      
    } else if (section.type === 'heading3') {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text(section.content, margin + 3, yPosition);
      yPosition += 6;
      
    } else if (section.type === 'bullet') {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text('•', margin + 5, yPosition);
      
      const bulletLines = doc.splitTextToSize(section.content, contentWidth - 10);
      bulletLines.forEach((line: string, index: number) => {
        doc.text(line, margin + 10, yPosition);
        if (index < bulletLines.length - 1) {
          yPosition += 5;
          checkPageBreak(5);
        }
      });
      yPosition += 6;
      
    } else if (section.type === 'paragraph') {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const paraLines = doc.splitTextToSize(section.content, contentWidth);
      paraLines.forEach((line: string) => {
        checkPageBreak(5);
        doc.text(line, margin, yPosition);
        yPosition += 5;
      });
      yPosition += 3;
    }
  }
  
  // ==========================================
  // FOOTER
  // ==========================================
  
  const totalPages = doc.getNumberOfPages();
  
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // Slate-400
    doc.setFont('helvetica', 'italic');
    
    // Footer text
    doc.text(
      'Documento generado automáticamente por ARIA (Automated Requirements & Intelligent Artifacts)',
      margin,
      pageHeight - 10
    );
    
    // Page numbers
    doc.text(
      `Página ${i} de ${totalPages}`,
      pageWidth - margin - 20,
      pageHeight - 10
    );
    
    // Confidential notice
    doc.setFontSize(7);
    doc.text(
      'CONFIDENCIAL - Kashio © 2026',
      margin,
      pageHeight - 5
    );
  }
  
  // Return as Blob
  return doc.output('blob');
}

/**
 * Parse markdown content into structured sections
 */
function parseMarkdownSections(markdown: string): Array<{type: string, content: string}> {
  const lines = markdown.split('\n');
  const sections: Array<{type: string, content: string}> = [];
  
  for (let line of lines) {
    line = line.trim();
    if (!line) continue;
    
    // Headings
    if (line.startsWith('### ')) {
      sections.push({ type: 'heading3', content: line.replace('### ', '') });
    } else if (line.startsWith('## ')) {
      sections.push({ type: 'heading2', content: line.replace('## ', '') });
    } else if (line.startsWith('# ')) {
      sections.push({ type: 'heading1', content: line.replace('# ', '') });
    }
    // Bullet points
    else if (line.startsWith('* ') || line.startsWith('- ')) {
      sections.push({ type: 'bullet', content: line.replace(/^[*-] /, '') });
    }
    // Bold text (convert to regular for PDF)
    else if (line.includes('**')) {
      const cleaned = line.replace(/\*\*/g, '');
      sections.push({ type: 'paragraph', content: cleaned });
    }
    // Regular paragraph
    else {
      sections.push({ type: 'paragraph', content: line });
    }
  }
  
  return sections;
}

/**
 * Download PDF to user's device
 */
export function downloadPDF(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generate and download artifact PDF
 * 
 * @param content - Generated content from Gemini
 * @param metadata - Artifact metadata
 * @returns PDF blob
 */
export async function generateAndDownloadArtifact(
  content: string,
  metadata: ArtifactMetadata
): Promise<Blob> {
  const pdfBlob = await generatePDF(content, metadata);
  
  const filename = `${metadata.gate}_${metadata.artifactId}_${metadata.version}.pdf`;
  downloadPDF(pdfBlob, filename);
  
  return pdfBlob;
}

/**
 * Generate PDF and upload to Cloud Storage (browser-compatible)
 * 
 * Note: Requires signed URL from backend
 */
export async function generateAndUploadArtifact(
  content: string,
  metadata: ArtifactMetadata,
  getSignedUrlFn: () => Promise<string>
): Promise<{ pdfBlob: Blob; uploadUrl: string }> {
  // 1. Generate PDF
  const pdfBlob = await generatePDF(content, metadata);
  
  // 2. Get signed URL from backend (would be API call in production)
  const signedUrl = await getSignedUrlFn();
  
  // 3. Upload to Cloud Storage
  await fetch(signedUrl, {
    method: 'PUT',
    body: pdfBlob,
    headers: {
      'Content-Type': 'application/pdf'
    }
  });
  
  return { pdfBlob, uploadUrl: signedUrl };
}

/**
 * Preview PDF in new tab
 */
export function previewPDF(blob: Blob) {
  const url = URL.createObjectURL(blob);
  window.open(url, '_blank');
}

/**
 * Generate simple text PDF (quick version)
 */
export function generateSimplePDF(
  title: string,
  content: string,
  metadata?: Partial<ArtifactMetadata>
): Blob {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 20, 20);
  
  // Content
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const lines = doc.splitTextToSize(content, 170);
  doc.text(lines, 20, 35);
  
  // Footer
  if (metadata) {
    doc.setFontSize(8);
    doc.text(`Generated by ${metadata.generatedBy || 'ARIA'}`, 20, 280);
  }
  
  return doc.output('blob');
}

export default {
  generatePDF,
  downloadPDF,
  generateAndDownloadArtifact,
  generateAndUploadArtifact,
  previewPDF,
  generateSimplePDF
};

